name: Hotfix to Main

on:
  push:
    branches:
      - hotfix

permissions:
  contents: write

jobs:
  merge-hotfix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout completo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configura Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Mesclar hotfix em main
        run: |
          git checkout main
          git merge --no-ff hotfix -m "runner: merge hotfix into main"
          
      - name: Push para main
        run: git push origin main
